create database my_database;
use my_database;

select * from cleaned_purchase_data;
select count(*) from cleaned_purchase_data;

#what is the the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue 
from cleaned_purchase_data
group by gender;

# which customer used discount but still spent more than average purchase amount?
select customer_id,purchase_amount
from cleaned_purchase_data
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from cleaned_purchase_data);

#Which are top 5 products with highest average review rating?

select item_purchased, round(avg(review_rating),2) as Average_ratings
from cleaned_purchase_data
group by item_purchased
order by Average_ratings desc
limit 5;

# compare the average purchase amount between standard and express shipping

select shipping_type,round(avg(purchase_amount),2 )as Average_Amount
from cleaned_purchase_data
where shipping_type in ('standard','express')
group by shipping_type;

# Do subscribed customers spend more? compare average spend and total revenue beetween subscriber and non-subscriber

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as Average_Spend,
round(SUM(purchase_amount),2) as total_revenue
from cleaned_purchase_data
group by subscription_status
order by total_revenue,Average_spend desc;

#which 5 products have the highest percentage of purchase with discounts applied

select item_purchased,
round(100 * sum(case when discount_applied ='yes' then 1 else 0 end )/ count(*),2) as discount_rate
from cleaned_purchase_data
group by item_purchased
order by discount_rate desc
limit 5;

# Segment customers into new,returning and loyal based on their total number of previous and show the count of each segment

with customer_type as (
select customer_id,previous_purchases,
case
    when previous_purchases= 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from cleaned_purchase_data
)
select customer_segment,count(*) as Number_of_customers
from customer_type
group by customer_segment

# Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribers
select subscription_status,
count(customer_id) as repeat_customers
from cleaned_purchase_data
where previous_purchases> 5
group by subscription_status

#Total revenue contribution by each age group

select age_group,
sum(purchase_amount) as Total_revenue
from cleaned_purchase_data
group by age_group
order by total_revenue desc;
